apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab11-app.fullname" . }}-secrets
  labels:
    {{- include "lab11-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc | quote }}
  password: {{ .Values.secrets.password | b64enc | quote }}
