apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab12-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lab12-app
  template:
    metadata:
      labels:
        app: lab12-app
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: lab12-app-env
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lab12-app-pvc
      - name: config
        configMap:
          name: lab12-app-config
