replicaCount: 1

image:
  repository: myapp
  tag: latest
  pullPolicy: IfNotPresent

config:
  appName: "visits-counter-app"
  environment: "production"
  logLevel: "INFO"

persistence:
  accessMode: ReadWriteOnce
  size: 100Mi
  storageClass: ""

service:
  type: ClusterIP
  port: 5000
